config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :stocks
  resources :locations
  get 'session/cart'

  resources :orders
  resources :products do
    member do 
      get '/new_transfer', to: 'products#new_transfer'
    end
  end 
  root 'static_pages#home'
  get 'users/new'
  
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/home', to: 'static_pages#home'
  
  get '/orders', to: 'users#orders'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/add_to_cart',  to: 'sessions#add_to_cart'
  get '/cart', to: 'sessions#show_cart'
  resources :users do
    member do
      get :orders
    end
  end
  
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :from_location, class_name: "Location"
  belongs_to :to_location, class_name: "Location"
  belongs_to :product
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  before_action :shopassistant
  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    if params.has_key?(:barcode)
      product = Product.find_by(barcode:params[:barcode])
      if(product)
        @transfer = product.transfers.build
      else
        flash[:danger] = "Product does not exist"
        redirect_to new_product_path, barcode: params[:barcode]
      end
    else
      @transfer = Transfer.new()
    end
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    ActiveRecord::Base.transaction do
      @transfer = current_user.transfers.new(transfer_params)
      from_stock = Stock.create_with(quantity:0).find_or_create_by!(location_id:@transfer.from_location_id, product_id:@transfer.product_id)
      to_stock = Stock.create_with(quantity:0).find_or_create_by!(location_id:@transfer.to_location_id, product_id:@transfer.product_id)
      if(from_stock.location.name!="Suppliers" && from_stock.quantity < @transfer.quantity)
        flash[:danger]="Not Enough Stock"
        render :new and return
      end
      from_stock.decrement!(:quantity, @transfer.quantity.to_i) if(from_stock.location.name!="Suppliers")
      to_stock.increment!(:quantity, @transfer.quantity.to_i)
      respond_to do |format|
        if @transfer.save
          format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
          format.json { render :show, status: :created, location: @transfer }
        else
          format.html { render :new }
          format.json { render json: @transfer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:from_location_id, :to_location_id,:product_id, :quantity, :details)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/edit.html.erb
<% provide(:title, 'Edit Transfer') %>
<% provide(:action, 'Edit Transfer') %>
<h1>Editing Transfer</h1>

<%= render 'shared/transfer_form', transfer: @transfer %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>From location</th>
      <th>To location</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.user.name %></td>
        <td><%= transfer.from_location.name %></td>
        <td><%= transfer.to_location.name %></td>
        <td><%= transfer.product.name %></td>
        <td><%= transfer.quantity %></td>
        <td><%= transfer.details %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<% provide(:title, 'New Transfer') %>
<% provide(:action, 'Transfer') %>
<h1>New Transfer</h1>

<%= render 'shared/transfer_form', transfer: @transfer %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @transfer.user.name %>
</p>

<p>
  <strong>From location:</strong>
  <%= @transfer.from_location.name %>
</p>

<p>
  <strong>To location:</strong>
  <%= @transfer.to_location.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @transfer.product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @transfer.quantity %>
</p>

<p>
  <strong>Details:</strong>
  <%= @transfer.details %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>