config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :stocks
  resources :locations
  get 'session/cart'

  resources :orders
  resources :products do
    member do 
      get '/new_transfer', to: 'products#new_transfer'
    end
  end 
  root 'static_pages#home'
  get 'users/new'
  
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/home', to: 'static_pages#home'
  
  get '/orders', to: 'users#orders'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/add_to_cart',  to: 'sessions#add_to_cart'
  get '/cart', to: 'sessions#show_cart'
  resources :users do
    member do
      get :orders
    end
  end
  
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :stocks
  has_many :transfers
  has_many :locations, through: :stocks
  
  mount_uploader :picture, PictureUploader
  validates :name, presence: true
  validates :price, presence: true
  validate  :picture_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :new_transfer]
  before_action :shopkeeper, only: [:new, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all.paginate(page: params[:page]);
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    if params.has_key?(:barcode)
      @product=Product.build(barcode: :barcode)
    else
      @product = Product.new()
    end
  end
  
  def new_transfer
    @transfer = @product.transfers.build
    render :template => "transfers/new"
  end
  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    new_params = product_params
    new_params[:stock]=0
    @product = Product.new(new_params)
    if @product.save
      flash[:success] = "Product successfully created."
      redirect_to @product
    else
      render 'new'
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock, :barcode, :picture)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(product, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :barcode %>
        <%= f.text_field :barcode, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    
      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    
      <div class="field">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>
      
      <span class="picture">
        <%= f.label :picture %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
      </span>
      
      <div class="actions">
        <%= f.submit("Submit",class: 'btn btn-primary') %>
      </div>
      
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#product_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/products/_product.html.erb
<div id="product-<%= product.id %>" class="col-sm-4 col-md-3 product">
  <div class="center">
    <%if product.picture?%>
      <%= link_to image_tag(product.picture.url, alt: product.name, size: "200"), product %>
    <% else %>
      <%= link_to image_tag("delivery.jpg", alt: "Default Product Picture", size: "200"), product %>
    <% end %>
  </div>
  <div class="name center">
      <%= link_to product.name, product %>
      <% if !!current_user && current_user.role == 1 %>
        <br/><%= link_to 'Edit', edit_product_path(product) %>
        | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
  </div>
  <br/>
  <div class="price">Price: €<%= product.price %></div>
  <br/>
  <div class="decription">Description: <%= product.description.truncate_words(5) %></div>
  <div class="stock">Stock available:<%= product.stocks.sum(:quantity) %></div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% provide(:title, 'Products') %>
<h1>All Products</h1>
<%= if !!current_user && current_user.role == 1
        link_to 'Add New Product', new_product_path, class: "btn btn-primary btn-block"
end %>
<div class="container-fluid center", id="products-index">
  <%= render @products %>
  <%= will_paginate @products %>
</div>
</ul>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>
<div class="container" id="show-product">
  <div class="col-sm-3">
    <%if @product.picture?%>
      <%= link_to image_tag(@product.picture.url, alt: @product.name, size: "200"), @product %>
    <% else %>
      <%= link_to image_tag("delivery.jpg", alt: "Default Product Picture", size: "200"), @product %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <div class="name">
      <h1><%= @product.name %></h1>
      <div class='center'>
      <% if !!current_user && current_user.role == 1 %>
      | <%= link_to 'Edit', edit_product_path(@product) %>
      | <%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <% if !!current_user && current_user.role > 0 %>
      | <%= link_to 'Transfer Stock', new_transfer_product_path(@product) %>
      <% end %>
      </div>
    </div>
    <hr>
    <div class="price">Price: <%= @product.price %></div>
    <div class="decription">Description: <%= @product.description %></div>
    <div class="stock">Stock: <%= @product.stocks.sum(:quantity) %></div>
  </div>
  <div class="col-sm-3">
    <form action = "<%= add_to_cart_url %>" method="get">
      Quantity x <input type="number" name="quantity" value="1">
      <input type="hidden" name="id" value=<%= @product.id %>>
      <input type="submit" value="Add to cart" class= "btn btn-primary btn-block">
      <%= link_to 'Buy Now', "#", class: "btn btn-success btn-block"%>
      <%= link_to 'Back', products_path, class: "btn btn-default btn-block"%>
    </form>
  </div>
</div>