config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :stocks
  resources :locations
  get 'session/cart'

  resources :orders
  resources :products do
    member do 
      get '/new_transfer', to: 'products#new_transfer'
    end
  end 
  root 'static_pages#home'
  get 'users/new'
  
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/home', to: 'static_pages#home'
  
  get '/orders', to: 'users#orders'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/add_to_cart',  to: 'sessions#add_to_cart'
  get '/cart', to: 'sessions#show_cart'
  resources :users do
    member do
      get :orders
    end
  end
  
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Online Retail Shop
    by <a href="mailto:avinash.narayana@gmail.com?Subject=Online%20Retail%20Shop">
      Avinash N Regulagadda</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "Kwality Foods", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <% if logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Orders", orders_path %></li>
              <% if current_user.role == 1 %>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Locations", locations_path %></li>
                <li><%= link_to "Transfers", transfers_path %></li>
              <% end %>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up",   signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><%= link_to "Cart", cart_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Online Retail Shop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>